[package]
name = "rust-time-tracker"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_time_tracker"
path = "src/libraries/lib.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
users = "0.11"
