[package]
name = "rust-time-tracker"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_time_tracker"
path = "src/libraries/lib.rs"

[dependencies]
chrono = "0.4.38"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
users = "0.11"
